name: "test-on-push"
on: [push, pull_request]

jobs:
  # Ensure version numbers in various places match up
  ensure-same-version:
    runs-on: ubuntu-20.04
    steps:
      - name: install dependencies
        run: |
          pip install toml
      - name: Run check
        run: |
          python3 scripts/check_version_numbers.py

  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - name: install app dependencies and build it
      env:
        TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
      run: |
        npm install
        ./node_modules/.bin/rollup --config
        npm run tauri build
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
    - name: upload build artifact
      uses: actions/upload-artifact@v2
      with:
        path: |
          src-tauri/target/release/bundle/appimage/*.AppImage
          src-tauri/target/release/bundle/deb/*.deb
          src-tauri/target/release/bundle/msi/*.msi
